//
// Generated file, do not edit! Created by opp_msgtool 6.1 from packets/PublishMessage.msg.
//

#ifndef __PUBLISHMESSAGE_M_H
#define __PUBLISHMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class PublishMessage;
#include "PubSubMessage_m.h" // import PubSubMessage

/**
 * Class generated from <tt>packets/PublishMessage.msg:3</tt> by opp_msgtool.
 * <pre>
 * class PublishMessage extends PubSubMessage
 * {
 *     string data;
 * }
 * </pre>
 */
class PublishMessage : public ::PubSubMessage
{
  protected:
    omnetpp::opp_string data;

  private:
    void copy(const PublishMessage& other);

  protected:
    bool operator==(const PublishMessage&) = delete;

  public:
    PublishMessage();
    PublishMessage(const PublishMessage& other);
    virtual ~PublishMessage();
    PublishMessage& operator=(const PublishMessage& other);
    virtual PublishMessage *dup() const override {return new PublishMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getData() const;
    virtual void setData(const char * data);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PublishMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PublishMessage& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline PublishMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<PublishMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __PUBLISHMESSAGE_M_H

